### ISSUE TITLE
Usercentrics SDK crashes on devices with poor connection

### ISSUE THREAD

**Issue by VitaSokolova** [Usercentrics/android-sample#11]
I couldn't find a repository with SDK issues in general, sorry for posting it here even though it doesn't relate to android sample directly. Only to  Usercentrics SDK for Android. 

In My Android project I noticed a crash in crashlytics. 
```
Fatal Exception: com.usercentrics.sdk.errors.InitializationFailedException: Usercentrics initialization failed: Unable to initialise due to poor or no network connection.
       at com.usercentrics.sdk.UsercentricsInternal.onFailureInitializingSDKOffline(UsercentricsInternal.kt:135)
       at com.usercentrics.sdk.UsercentricsInternal.access$onFailureInitializingSDKOffline(UsercentricsInternal.kt:8)
       at com.usercentrics.sdk.UsercentricsInternal$initializeSDKOffline$3.invoke(UsercentricsInternal.kt:125)
       at com.usercentrics.sdk.UsercentricsInternal$initializeSDKOffline$3.invoke(UsercentricsInternal.kt:120)
       at com.usercentrics.sdk.v2.language.facade.LanguageFacade$resolveLanguage$2.invoke(LanguageFacade.kt:24)
       at com.usercentrics.sdk.v2.language.facade.LanguageFacade$resolveLanguage$2.invoke(LanguageFacade.kt:23)
       at com.usercentrics.sdk.v2.async.dispatcher.DispatcherCallback.setResult$usercentrics_release(DispatcherCallback.kt:26)
       at com.usercentrics.sdk.v2.async.dispatcher.Dispatcher$dispatch$1.invokeSuspend(Dispatcher.kt:20)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

I wonder how I can prevent my app from crashing, does it happen inside `   Usercentrics.initialize(context = this, options = options)` call?
I use `"com.usercentrics.sdk:usercentrics-ui:2.8.3"` version

**Comment by uc-rreis** [comment]
Hello @VitaSokolova 

could you please open a ticket at https://usercentricssupport.zendesk.com/hc/en-us/requests/new with the details on the issue so we can have a look?

Cheers,
Rui

**Comment by VitaSokolova** [comment]
> Hello @VitaSokolova
> 
> could you please open a ticket at https://usercentricssupport.zendesk.com/hc/en-us/requests/new with the details on the issue so we can have a look?
> 
> Cheers, Rui

I've reported my issue there ✅

**Comment by uc-rreis** [comment]
Thanks, Viktoria!
I'll close this issue here then ;)
